shop/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _

from .decorators import unautthenticated_user
from . import views

app_name = 'accounts'
urlpatterns = [
    path(_('login/'), unautthenticated_user(views.LoginView.as_view()), name='login'),
    path(_('register/'), unautthenticated_user(views.RegisterView.as_view()), name='register'),
    path(_('logout'), views.LogoutView.as_view(), name='logout'),
    path(_('my-offers/'), include([
        path(_('<slug:status>'), login_required(views.MyProducts.as_view()), name='my-products'),
    ])),
]

shop/products/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
# from django.views.decorators.cache import cache_page
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'products'
urlpatterns = (
    path('', views.PromoListView.as_view(), name='promo-list'),
    path('get-city-location', views.GetCityLocation.as_view(), name='get-city-location'),
    path(_('offers/'), include([
        path('get-average-price/<slug:product_class>', views.GetAveragePrice.as_view(), name='get-average-price'),
        path(_('search'), views.SearchProductView.as_view(), name='search'),
        path(_('observed/'), include([
            path('', views.ObservedProductsView.as_view(), name='observed-offers'),
            path(_('transport'), views.TransportObservedProducts.as_view(), name='transport-observed-offers'),
            path('<slug:section>/<int:product_id>/', include([
                path(_('add'), views.AddObservedProduct.as_view(), name='add-observed-offer'),
                path(_('remove'), views.RemoveObservedProduct.as_view(), name='remove-observed-offer'),
            ])),
        ])),
        path(_('create/'), include([
            path('', TemplateView.as_view(template_name='products/kind_of_product_to_create.html'), name='kind-of-offer-to-create'),
            path('<slug:section>', login_required(views.CreateProductView.as_view()), name='create-product')
        ])),
        path(_('delete-product/<slug:product_class>/<int:product_id>'), login_required(views.DeleteProduct.as_view()), name='delete-product'),
        path('<slug:section>/<slug:product_slug>/', include([
            path('', views.DetailView.as_view(), name='detail'),
            path('show-phonenumber', views.ShowPhonenumber.as_view(), name='show-phonenumber'),
            path(_('send-email'), views.SendEmail.as_view(), name='send-email'),
        ])),
    ])),
)

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('products.urls')),
    path(_('accounts/'), include('accounts.urls')),
)

handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shop/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin = True
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    email                   = models.EmailField(max_length=60, unique=True)
    date_joined             = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login              = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin                = models.BooleanField(default=False)
    is_active               = models.BooleanField(default=True)
    is_staff                = models.BooleanField(default=False)
    is_superuser            = models.BooleanField(default=False)

    observed_cars           = models.ManyToManyField('products.Car', blank=True)
    observed_parts          = models.ManyToManyField('products.Part', blank=True)
    observed_motorcycles    = models.ManyToManyField('products.Motorcycle', blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = AccountManager()

    @property
    def username(self):
        return self.email[:int(self.email.index('@'))]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

shop/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm#, UserChangeForm

from .models import Account

class AuthenticateForm(forms.ModelForm):
    email = forms.EmailField(
        label = 'Email',
        required = True,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
            }
        )
    )

    password = forms.CharField(
        label = 'Password',
        required = True,
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
            }
        )
    )

    class Meta:
        model = Account
        fields = (
            'email',
            'password',
        )

    def clean(self, *args, **kwargs):
        if self.is_valid():
            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user is not None:
                if not user.is_active:
                    raise forms.ValidationError('This user has been disabled')
            else:
                raise forms.ValidationError('Invalid login')

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        label = 'Email',
        required = True,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
            }
        )
    )

    password1 = forms.CharField(
        required = True,
        label = 'Password',
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
                'id': 'password-input',
            }
        )
    )

    password2 = forms.CharField(
        required = True,
        label = 'Confirm password',
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
            }
        )
    )

    class Meta:
        model = Account
        fields = (
            'email',
            'password1',
            'password2',
        )

shop/accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib.auth import login, logout, authenticate

from queryset_sequence import QuerySetSequence
from products.models import Car, Part, Motorcycle
from . import forms

class LoginView(generic.FormView):
    template_name = 'accounts/login.html'
    form_class = forms.AuthenticateForm

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)

        login(self.request, user)

        next = self.request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('/')

class RegisterView(generic.CreateView):
    template_name = 'accounts/register.html'
    form_class = forms.RegisterForm

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get('email')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(email=email, password=raw_password)

        login(self.request, user)

        next = self.request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('/')

class LogoutView(generic.View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

class MyProducts(generic.ListView):
    template_name = 'accounts/my_products.html'
    context_object_name = 'products'

    def get_products(self, status):
        if status == 'active':
            cars = Car.objects.filter(seller=self.request.user)
            parts = Part.objects.filter(seller=self.request.user)
            motorcycles = Motorcycle.objects.filter(seller=self.request.user)
        elif status == 'pending':
            cars = Car.pending_objects.filter(seller=self.request.user)
            parts = Part.pending_objects.filter(seller=self.request.user)
            motorcycles = Motorcycle.pending_objects.filter(seller=self.request.user)

        cars = cars if cars.exists() else Car.objects.none()
        parts = parts if parts.exists() else Part.objects.none()
        motorcycles = motorcycles if motorcycles.exists() else Motorcycle.objects.none()

        order = f"{'-' if self.request.GET.get('reverse', 'True') == 'True' else ''}{self.request.GET.get('lookup', 'pub_date')}"

        return QuerySetSequence(cars, parts, motorcycles).prefetch_related('images').order_by(order)

    def get_queryset(self):
        status = self.kwargs.get('status')
        qs = self.get_products(status)

        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(MyProducts, self).get_context_data(*args, **kwargs)

        context['active_products_count'] = self.get_products('active').count()
        context['pending_products_count'] = self.get_products('pending').count()

        return context

    def get(self, request, *args, **kwargs):
        status = self.kwargs.get('status')

        if not self.get_products('pending').count() and status == 'pending':
            return HttpResponseRedirect(reverse('accounts:my-products', kwargs={'status': 'active'}))
        return super(MyProducts, self).get(request, *args, **kwargs)

shop/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}Login Page{% endblock %}

{% load i18n %}
{% load static %}

{% block body_content %}

<div class="container2">
    <div class="container">
        <div class="card shadow-sm rounded-lg" id="navbar">
            <div class="card-body">
                <form method="post"> {% csrf_token %}
                    <h1 class="mb-4">{% trans 'Login' %}</h1>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <div class="animated-label">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <button class="btn btn-info px-4">{% trans 'Login' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}{% endblock %}

shop/accounts/templates/accounts/my_products.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% endblock %}

{% load static %}
{% load humanize %}
{% load translate %}
{% load classes %}

{% block body_content %}

{% url 'accounts:my-products' status='active' as my_active_products %}
{% url 'accounts:my-products' status='pending' as my_pending_products %}

<div class="container mt-5">
    <h3 class="font-weight-normal text-center" style="letter-spacing: 1px;">Your offers</h3>

    <div class="btn-group btn-group-justified mb-5 d-flex justify-content-center">
        <a href="#" class="btn btn-light shadow-sm px-5 py-3 mr-3">Statistics</a>
        <a href="{% url 'accounts:my-products' status='active' %}" class="btn btn-light shadow-sm px-5 py-3 mr-3 {% if request.path == my_active_products or request.path == my_pending_products %}bg-primary text-white active" aria-disabled="true" style="cursor: default;"{% else %}"{% endif %}>Announcements</a>
        <a href="#" class="btn btn-light shadow-sm px-5 py-3 mr-3">Messages</a>
        <a href="#" class="btn btn-light shadow-sm px-5 py-3 mr-3">Payment</a>
        <a href="#" class="btn btn-light shadow-sm px-5 py-3">Settings</a>
    </div>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link px-5 py-3 text-dark {% if request.path == my_active_products %}active{% endif %}" href="{{ my_active_products }}">
                Active
                {% if active_products_count %}({{ active_products_count }}){% endif %}
            </a>
        </li>
        {% if pending_products_count %}
            <li class="nav-item">
                <a class="nav-link px-5 py-3 mx-2 text-dark {% if request.path == my_pending_products %}active{% endif %}" href="{{ my_pending_products }}">
                    Pending
                    {% if pending_products_count %}({{ pending_products_count }}){% endif %}
                </a>
            </li>
        {% endif %}
    </ul>
</div>

<div class="bg-white">
    <div class="card-body container">
        {% if products.exists %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" colspan="2">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr class="observed-product" id="product{{ forloop.counter }}" data-url="{% url 'products:delete-product' product_class=product|to_class_name|lower product_id=product.id %}"> <!--  data-product-class="{{ product|to_class_name|lower }}" data-product-id="{{ product.id }}" -->
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>
                                <a href="{% url 'products:detail' section=product|to_class_name|lower product_slug=product.slug %}" class="mx-auto">
                                    <img src="{% if product.images.exists %}{{ product.images.first }}{% else %}{% static 'images/imageNotFound.png' %}{% endif %}" class="shadow-sm" style="object-fit: fill;" width="148" alt="{{ product }}">
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'products:detail' section=product|to_class_name|lower product_slug=product.slug %}" style="font-size: 22px;" class="title text-decoration-none">{{ product.get_title|truncatechars:40 }}</a>

                                <br>
                                <button class="btn btn-success btn-sm shadow-sm mt-2 mr-2">
                                    Make unique
                                </button>
                            </td>
                            <td>
                                <p class="product-price font-weight-bold" style="background: transparent; position: static; padding-left: 0;">
                                    {{ product.price|floatformat:0|intcomma }}
                                    <sup>{{ product.currency }}</sup>
                                </p>
                            </td>
                            <td>
                                <button class="btn btn-light shadow-sm mr-2">
                                    Edit
                                    <i class="fas fa-edit"></i>
                                </button>
                                <button class="btn btn-light shadow-sm">
                                    View
                                    <i class="far fa-eye"></i>
                                </button>

                                <br> <br>
                                <button class="btn btn-outline-danger shadow-sm mr-2 delete-product" data-product="{{ forloop.counter }}">
                                    <i class="fas fa-trash-alt"></i>
                                    Delete
                                </button>
                                <button class="btn btn-outline-success shadow-sm mr-2">
                                    Active
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
                <div class="text-center">
                    <i class="fas fa-car-alt fa-7x mx-3"></i>
                    <i class="fas fa-motorcycle fa-7x mx-3"></i>
                    <i class="fas fa-tools fa-7x mx-3"></i>
                    <h1>
                        {% if view.kwargs.status == 'active' %}
                            {% trans "Currently you don't have any active product" %}
                        {% elif view.kwargs.status == 'pending' %}
                            {% trans "Currently you don't have any pending product" %}
                        {% endif %}
                    </h1>
                    <a type="button" href="{% url 'products:kind-of-offer-to-create' %}" class="btn btn-danger px-4 py-2">
                        <i class="fas fa-plus fa-lg"></i>
                        Add an announcement
                    </a>
                </div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block extra_js %}

<script>
    $(document).ready(function() {
        $('.delete-product').click(function() {
            const $element = $('#product' + $(this).attr('data-product'))
            const url = $element.attr('data-url')

            $.ajax({
                method: 'GET',
                url: url,
                success: data => {
                    console.log(data)
                    $element.fadeOut(500)
                }
            })
        })
    })
</script>

{% endblock %}

shop/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %}Register Page{% endblock %}

{% load i18n %}
{% load static %}

{% block body_content %}

<div class="container2">
    <div class="container">
        <div class="card shadow-sm rounded-lg">
            <div class="card-body">
                <form method="post"> {% csrf_token %}
                    <h1 class="mb-4">{% trans 'Register' %}</h1>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="form-group">
                        {% if form.email.errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="animated-label">
                            {{ form.email }}
                            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                        </div>
                    </div>
                    <div class="form-group">
                        {% if form.password1.errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.password1.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="animated-label">
                            {{ form.password1 }}
                            <label for="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
                        </div>
                    </div>
                    <div class="form-group">
                        {% if form.password2.errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.password2.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="animated-label">
                            {{ form.password2 }}
                            <label for="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
                        </div>
                    </div>
                    <button class="btn btn-info px-4">{% trans 'Register' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}{% endblock %}