shop/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _

from .decorators import unautthenticated_user
from . import views

app_name = 'accounts'
urlpatterns = [
    path(_('login/'), unautthenticated_user(views.LoginView.as_view()), name='login'),
    path(_('register/'), unautthenticated_user(views.RegisterView.as_view()), name='register'),
    path(_('logout'), views.LogoutView.as_view(), name='logout'),
    path(_('my-offers/'), include([
        path(_('<slug:status>'), login_required(views.MyProducts.as_view()), name='my-products'),
    ])),
]

shop/products/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
# from django.views.decorators.cache import cache_page
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'products'
urlpatterns = (
    path('', views.PromoListView.as_view(), name='promo-list'),
    path('get-city-location', views.GetCityLocation.as_view(), name='get-city-location'),
    path(_('offers/'), include([
        path('get-average-price/<slug:product_class>', views.GetAveragePrice.as_view(), name='get-average-price'),
        path(_('search'), views.SearchProductView.as_view(), name='search'),
        path(_('observed/'), include([
            path('', views.ObservedProductsView.as_view(), name='observed-offers'),
            path(_('transport'), views.TransportObservedProducts.as_view(), name='transport-observed-offers'),
            path('<slug:section>/<int:product_id>/', include([
                path(_('add'), views.AddObservedProduct.as_view(), name='add-observed-offer'),
                path(_('remove'), views.RemoveObservedProduct.as_view(), name='remove-observed-offer'),
            ])),
        ])),
        path(_('create/'), include([
            path('', TemplateView.as_view(template_name='products/kind_of_product_to_create.html'), name='kind-of-offer-to-create'),
            path('<slug:section>', login_required(views.CreateProductView.as_view()), name='create-product')
        ])),
        path(_('delete-product/<slug:product_class>/<int:product_id>'), login_required(views.DeleteProduct.as_view()), name='delete-product'),
        path('<slug:section>/<slug:product_slug>/', include([
            path('', views.DetailView.as_view(), name='detail'),
            path('show-phonenumber', views.ShowPhonenumber.as_view(), name='show-phonenumber'),
            path(_('send-email'), views.SendEmail.as_view(), name='send-email'),
        ])),
    ])),
)

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('products.urls')),
    path(_('accounts/'), include('accounts.urls')),
)

handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shop/templates/partials/_footer.html
{% load static %}
{% load i18n %}

<footer id="site-footer">
    <div class="float-left">
        <img src="{% static 'images/logo.png' %}" width="300" alt="" class="img-fluid">
        <p class="footer-company-name">aWheele © 2020</p>
    </div>
    <div class="float-right">
        <p class="footer-company-about">
            <span>{% trans 'Information' %}</span>
            {% trans 'The website was created by' %} <a href="#" class="font-weight-bold text-white">Kamil Głuchowski</a>

        </p>
        <div class="footer-icons">
            <a href="https://www.google-play.com"><i class="fab fa-google-play"></i></a>
            <a href="https://www.apple.com"><i class="fab fab fa-apple"></i></a>
            <a href="https://www.youtube.com"><i class="fab fab fa-youtube"></i></a>
            <a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com"><i class="fa fab fa-instagram"></i></a>
        </div>
    </div>
</footer>

shop/templates/partials/_navbar.html
{% url 'accounts:register' as register %}
{% url 'accounts:login' as login %}
{% url 'products:observed-offers' as observed_offers %}
{% url 'accounts:my-products' status='active' as my_active_products %}
{% url 'accounts:my-products' status='pending' as my_pending_products %}

{% load i18n %}
{% load static %}

<div class="navbar-sticky">
    <nav class="navbar navbar-inverse navbar-expand-md navbar-light bg-light shadow-sm">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'products:promo-list' %}"><img src="{% static 'images/logo.png' %}" alt="" height="30" width="150"></a>
        </div>
        <button class="navbar-toggler" type="button" data-target="#navbar" data-toggle="collapse" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item border-left px-2">
                    <a href="{{ observed_offers }}" class="nav-link {% if request.path == observed_offers %}active{% endif %}">
                        <i class="fas fa-star"></i>
                        {% trans 'Observed' %}
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown border-left px-2">
                        <a href="#" class="nav-link dropdown-toggle {% if request.path == my_active_products or request.path == my_pending_products %}active{% endif %}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user-alt"></i>
                            {{ user }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item {% if request.path == my_active_products or request.path == my_pending_products %}active{% endif %}" href="{{ my_active_products }}">
                                <i class="fas fa-house-user"></i>
                                My aWheele
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> {% trans 'Logout' %}</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item border-left px-2">
                        <a class="nav-link {% if request.path == register %}active{% endif %}" href="{{ register }}{% if not request.path == register and not request.path == login %}?next={{ request.get_full_path_info  }}{% endif %}"><i class="fas fa-user-plus"></i> {% trans 'Register' %}</a>
                    </li>
                    <li class="nav-item border-left px-2">
                        <a class="nav-link {% if request.path == login %}active{% endif %}" href="{{ login }}{% if not request.path == register and not request.path == login  %}?next={{ request.get_full_path_info  }}{% endif %}"><i class="fas fa-plus"></i> {% trans 'Login' %}</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="btn btn-primary text-white font-weight-bold h-100 nav-link" style="font-size: smaller;" role="button" href="{% url 'products:kind-of-offer-to-create' %}">
                        <i class="fas fa-plus"></i>
                        {% trans 'Add an announcement' %}
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="alert alert-danger text-center m-0 py-1 media-fixed-bottom rounded-0" role="alert">
        <span>
            <strong>COVID-19: </strong>
            <span class="text-danger">#{% trans 'stayathome' %}</span> //  {% trans 'Active information and recomendation for buyers and sellers on aWheele' %}
        </span>
    </div>
</div>

shop/templates/partials/_paginator.html
{% load i18n %}
{% load params %}

{% if is_paginated %}
    <nav class="mt-5">
        <h6 class="text-center">{% blocktrans with page_number=page_obj.number pages=page_obj.paginator.num_pages %}Page {{ page_number }} of {{ pages }}{% endblocktrans %}</h6>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a href="?{% param_replace page=page_obj.previous_page_number %}" class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
            {% endif %}

            {% if page_obj.number|add:'-4' > 1 %}
                <li class="page-item"><a href="?{% param_replace page=page_obj.number|add:'-5' %}" class="page-link">&hellip;</a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active" style="z-index: 0;"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                    <li class="page-item" style="z-index: 0;"><a href="?{% param_replace page=i %}" class="page-link">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if paginator.num_pages > page_obj.number|add:'4' %}
                <li class="page-item"><a href="?{% param_replace page=page_obj.number|add:'5' %}" class="page-link">&hellip;</a></li>
            {% endif %}

            {% if page_obj.has_next %}
                <li class="page-item"><a href="?{% param_replace page=page_obj.next_page_number %}" class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

shop/templates/partials/_socialmedia_nav.html
<nav class="d-flex flex-column bd-highlight position-fixed shadow-sm border media-nav" style="top: 25%;">
    <a href="https://www.google-play.com" target="_blank" class="p-2 bg-light">
        <i class="fab fa-google-play fa-lg"></i>
    </a>
    <a href="https://www.apple.com" target="_blank" class="p-2  bg-light">
        <i class="fab fa-apple fa-lg"></i>
    </a>
    <a href="https://www.youtube.com" target="_blank" class="p-2 bg-light">
        <i class="fab fa-youtube fa-lg"></i>
    </a>
    <a href="https://www.facebook.com" target="_blank" class="p-2 bg-light">
        <i class="fab fa-facebook-square fa-lg"></i>
    </a>
    <a href="https://www.instagram.com" target="_blank" class="p-2 bg-light">
        <i class="fab fa-instagram-square fa-lg"></i>
    </a>
</nav>